# Generated by Django 2.2.2 on 2019-06-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='txt',
            new_name='text',
        ),
    ]
